# application-dev.yml
# DO NOT set spring.profiles.active here - it's already set in application.yml

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/stayease_db
    username: postgres
    password: Shinei-Nouzen
  
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  
  liquibase:
    contexts: dev
    drop-first: false

logging:
  level:
    root: INFO
    com.stayease: DEBUG
    org.springframework.web: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

server:
  port: 8080